development: &default
  adapter: postgresql
  encoding: utf8
  database: felipenorato_is_proficiency_test_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost

staging:
  <<: *default
  database: felipenorato_is_proficiency_test_staging

test:
  <<: *default
  database: felipenorato_is_proficiency_test_test

production:
  <<: *default
  database: felipenorato_is_proficiency_test_production